# CI文档地址：http://wiki.info/pages/viewpage.action?pageId=47414115
include:
  - project: "ywzc/ci-template"
    ref: "2.0"
    file: "template.yml"

variables:
  FTP_BASE: "/adminaola/production/snowball"
  PACKAGE_NAME: "tianti-web"
  NODE_VERSION: "v16.14.0"

test-npm:
  extends:
    - .test
    - .npm-build
  script:
    - source ${ENV}
    - nvm install ${NODE_VERSION}
    - npm install -g pnpm
    - npm install -g nrm
    - pnpm install
    - nrm add repo $TEST_REPO
    - nrm use repo
    - echo "$NPM_PUBLISH_ACCESS_TOKEN" >> .npmrc
    - pnpm run release:prod
    - mkdir -p tianti-web/resource/snowball/
    - mv dist/* tianti-web/resource/snowball/
  tags:
    - ftp

test-deploy:
  extends:
    - .test
    - .deploy-scp
  variables:
    SERVER: 10.17.2.212
    SITE_PATH: "/home/site/tianti-web/"

npm-publish:
  extends:
    - .test
    - .upload-zip
# production-npm:
#   extends:
#     - .master
#     - .npm-build
#   script:
#     - source ${ENV}
#     - nvm install ${NODE_VERSION}
#     - npm install -g pnpm
#     - pnpm install
#     - mv ${NPM_PUBLISH_ACCESS_TOKEN} ~/.npmrc
#     - pnpm run release:prod
#     - mkdir -p tianti-web/resource/snowball/
#     - mv dist/* tianti-web/resource/snowball/
#   artifacts:
#     name: tianti-web
#     paths:
#       - tianti-web
#   tags:
#     - ftp

# production-upload:
#   extends:
#     - .test
#     - .upload-zip
